---
version: "3.8"

services: 

    db:
        image: mysql:8.0.26
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lumen
            MYSQL_USER: lumen
            MYSQL_PASSWORD: lumen
        volumes: 
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        networks: 
            dockernet:
                ipv4_address: 192.168.42.12

volumes: 
    db_data:

networks:
    dockernet:
        ipam:
            driver: default
            config:
                - subnet: "192.168.42.0/24"
